spring.application.name=jpa

# COnfiguração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/aula_spring
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# mudamos para false em produção para não ter logs desnecessários
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true